public class Testrectangle{
       public static testMethod void method(){
       integer area;
       integer perimeter;
       Rectangle parameters=new Rectangle(5,6);
       area=parameters.area();
       perimeter=parameters.perimeter();
       parameters.getvalues();
       parameters.setValues(10,12);
       parameters.area();
       perimeter=parameters.perimeter();
       parameters.getValues();
      
       }
}